wireguard:
  server:
    name: vpn
    private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31383835363230656133336265633939636233643866323963363538326133326537666632313564
          3563386132346465626636633762623439313133356132610a353031633136303363333436633635
          38373762376631663738353962333036643566653432333936653732663534656664343131346439
          6664653931333530340a333735396463333862313564316630356538613936653830316439313966
          32393230326664313265386362316539663436643436646161656362353366366632396363383630
          3239303237316563323637323863636532323534633834356138
    public_key: Gi+5as22llOJLJtUj45vJ3oWgPBMFW9I0XbTJDoErBM=
    addresses:
      - 192.168.9.4/32
  clients:
    - Robotozon:
        public_key: eFk0j9kiv4Gpdxu2JytMN0VqWu0LKZUXM51dvIDVyjE=
        allowed_ips: 0.0.0.0/0
        endpoint_host: vpn.robotozon.com
        endpoint_port: 51820
        route_allowed_ips: 1
        persistent_keepalive: 25
