---
- name: root
  user:
    name: "root"
    state: present
    comment: "Root User"
    password: "$6$3cgTYm/q1uBehvkE$6aXutnYtPeLy8zexyKj/MXEBrF1N78RMkJT9pfQNvNewbsR7.kcjU1afb6g9fG8BM/WoJteaamKYoWu1T1Lgs."
    groups:
      - "root"
    create_home: true
    home: "/root"
    shell: "/bin/zsh"

- name: skingry
  user:
    name: "skingry"
    state: present
    comment: "Seth Kingry"
    password: "$6$GhEhf5/V4n1PRi/8$FFe5jdojDjmFkxB2dV96xUwP1jQ8JNAR64r8Hjt3p6Iq.1btCyOFgMcfd.5Ekbx/0B7/Yyd5dG1Ehip/4deQK0"
    groups:
      - "docker"
      - "sudo"
    create_home: true
    home: "/home/skingry"
    shell: "/bin/zsh"

- name: SSH Key - skingry@Carbon
  authorized_key:
    user: "skingry"
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMDTUyoLahekJntWK1Zm+2h60hZ7XbjDX7jYEsnBO/qJ skingry@Carbon"

- name: SSH Key - skingry@iPad
  authorized_key:
    user: skingry
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID86YyPyCCNXvPMh3SOrTWsPr5eEqSsyHThnJXLAVISL skingry@iPad"

- name: hush login - skingry
  file:
    path: "/home/skingry/.hushlogin"
    owner: "skingry"
    group: "skingry"
    access_time: preserve
    modification_time: preserve
    state: touch
...
