---
- name: certbot - pull and configure
  docker_image:
    name: certbot/dns-route53:latest
    source: pull

- name: certbot - setup cronjob for certificate renewal
  cron:
    name: Certbot Certificate Renewal
    minute: "0"
    hour: "3"
    job: "docker run --rm --name certbot -v '/opt/config/nginx/ssl:/config' -v '/opt/config/aws:/root/.aws' certbot/dns-route53 --config-dir /config renew >> /var/log/certbot.log"
