---
- name: makemkv - pull and configure
  docker_container:
    name: makemkv
    image: jlesage/makemkv
    pull: true
    devices:
      - /dev/sr0:/dev/sr0:rwm
      - /dev/sg3:/dev/sg3:rwm
    env:
      USER_ID: "65534"
      GROUP_ID: "65534"
    volumes:
      - /opt/config/makemkv:/config:rw
      - /data/shares/Media:/output:rw
      - /data/shares/Downloads:/storage:rw
    restart_policy: always
