---
- name: nzbget - pull and configure
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    pull: true
    network_mode: container:openvpn-client
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /opt/config/nzbget:/config:rw
      - /data/shares/Downloads:/downloads:rw
    restart_policy: always
