---
- name: Pull and configure container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: true
    network_mode: container:openvpn-client
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /opt/config/radarr:/config:rw
      - /data/shares/Media:/media:rw
      - /data/shares/Downloads:/downloads:rw
    restart_policy: always
