---
- name: Pull and configure container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    pull: true
    network_mode: container:openvpn-client
    env:
      PGID: "65534"
      PUID: "65534"
    volumes:
      - /opt/config/sonarr:/config:rw
      - /data/shares/Media/TV:/tv:rw
      - /data/shares/Media/TV_Children:/children:rw
      - /data/shares/Downloads:/downloads:rw
    restart_policy: always
