wireless:
  ssid: Kingry
  key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36356463346264663266396665383638333830633234623662653039376331313139663237636433
          6337383663343737333766396539643734626136626232660a646262613533303434636136663435
          66356161316566633966386639333764623339303361323163323435366437656237643262623265
          6333306530356361320a643732663635373866323164633264373362323235356137366463326662
          6463
