wireguard:
  server:
    name: vpn
    private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38333363333937356630303265383635306235323761633335383565356362353032323330323362
          6362616531386537393234386335313830313536346131640a393134646466353336386339336632
          37323432373138353132313466663639303761626135646431643536353564373331336432383663
          3836383033336133310a623865613437393266396533343565333937383233643038333162663634
          64303039623964313663396138663134363538326334353632633361383864626430346235666637
          3231356431386539376165333331663131656262656637643530
    public_key: eFk0j9kiv4Gpdxu2JytMN0VqWu0LKZUXM51dvIDVyjE=
  clients:
    - Tricorder:
        public_key: IKL4Rv1mCTqqyhMZMHJpyVSHFSd4OSP5Xy38BV8SsTE=
        allowed_ips: 192.168.9.2/32
    - Carbon:
        public_key: z5xP/MIUy4AurVowWY67rrNWb7WZsth3vEUE4ztUzkM=
        allowed_ips: 192.168.9.3/32
